## NumPy基础：数组和矢量计算
* ndarray,一个具有矢量算数运算和复杂广播能力的快速且节省空间的多维数组。
* 用于对整个数组进行快速运算的标准数学库（无需编写循环）
* 用于读写磁盘数据的工具以及用于操作内映射文件的工具
* 线性代数，随机数生成以及傅里叶变换等功能
* 用于集成C，C++，Fortran等语言编写的代码的工具
* NumPy还提供了一个简单易用的CAPI，所以python可以很容易的把数据传递给由低级语言编写的
外部库，并且也能获得相关的数据且以NumPy数组的形式返回输出。


### NumPy的ndarray：一种多维数组对象，
> 这个对象是一个快速而且灵活的大数据集容器,这个运算和标量运算一样。




In [1]:
import numpy as np
data = np.random.rand(2,3)
data



array([[0.05225395, 0.00194926, 0.07513964],
       [0.782554  , 0.8531682 , 0.33713604]])

In [2]:
data.shape
# 这个函数可以返回我们的数组的大小一些情况


(2, 3)

In [3]:
data.dtype
# 这个函数可以返回我们的数组内部的数据类型。

dtype('float64')

#### 创建一个ndarray
* 创建一个array数组的最简方法就是使用array函数。

In [4]:
data1 = [1,2,3,4,5,6,7,8,9]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 嵌套的多维数组会被array函数断行
data2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2.ndim

2

In [7]:
arr2.shape# 输出大小

(3, 3)

In [8]:
# 全为0
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
# 全为1
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
# 垃圾值表
np.empty((10,10),dtype=int)

array([[        -1, 2147483647,          1,          0,        640,
                 0,          1,          0,        896,          0],
       [       411,          0,        900,          0,        411,
                 0,        912,          0,        411,          0],
       [       940,          0,        411,          0,        988,
                 0,        411,          0,       1252,          0],
       [       411,          0,       1220,          0,        411,
                 0,       1272,          0,        411,          0],
       [      1240,          0,        411,          0,       1204,
                 0,        411,          0,       1276,          0],
       [       411,          0,          0,          0,          0,
                 0,          0,          0,          0,          0],
       [         0,          0,          0,          0,          0,
                 0,          0,          0,          0,          0],
       [         0,          0,          

|函数|说明|
|:--|:--|
|array|将输入数据(列表，元组，数组，或者其他序列的类型)转换成为ndrray，要么推断出dtype要么就显式指定的dtype，默认直接输入数据
|asarray|将输入的转换为ndarray，如果输入的本身就是一个ndarray就不进行复制
|arange|类似于内置的range，但返回的是一个ndarray而不是列表
|ones,ones_like|根据指定的形状和dtype来创建一个全为1的数组，ones_like则以另外一种数组的大小为参数，创建一个大小相同但是可能dtype不同的数组
|zeros，zeros_like|与ones差不多
|empty,empty_like|创建一个新数组，只分配内存地址空间而不填充任何值
|eye.identity|创建一个正方的NXN的单位矩阵(对角线为1，其余为0)



NumPy还具有相比于原版Python丰富的多的数据类型，以提供更加精确的数据运算，以及记录
int,uint,float,complex,bool,object,string_(固定长度的字符串),unicode(固定长度的unicode类型数据)



In [11]:
data = data * 5
data

array([[0.26126977, 0.00974631, 0.37569819],
       [3.91276998, 4.26584102, 1.68568018]])

In [12]:
data.astype(int)
# 使用这个astype函数可以直接转换个数，verynice


array([[0, 0, 0],
       [3, 4, 1]])

In [13]:
data3 = ['15','17','-5']
arr3 = np.array(data3)
arr3.astype(int)
# 这个方法甚至还能读取你的字符串数字，以方便直接打印出数字

array([15, 17, -5])

In [14]:
# 忘了讲创建ndarray数组了
arr4 = np.array(['12','17','-98'],dtype=np.string_)
# np.str_类型的每一个单元存储的是一个字符串，而np.string_其实本质上就是byte数组，每个单元不能使用字符串拼接。
arr4.astype(np.int)

array([ 12,  17, -98])

### 数组和标量之间的运算
```python
# arr = np.array([[1,2,3],[1,2,3]])
# ndarray可以进行标量之间的运算方式
# 你能想到的运算方式都可以广播到每一个小单元。
```


In [15]:
data5 = [[1,2,3],[4,5,6]]
arr5 = np.array(data5,dtype='float')
arr5 = arr5 ** 2
arr5

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

   ### 基本的索引与切片
> 数组的切片直接反应正在原数组上，而不会对复制品进行奇奇怪怪的运算，如果真想用这种操作你就需要使用copy函数。

#### array的索引




In [16]:
data6 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
arr6 = np.array(data6)
arr6

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [17]:
arr6[0]
# 取0是第一个大元素就是最大的中括号括起来的东西

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr6[0][0]
# 在切片下还可以往后切遇上面的同理

array([1, 2, 3])

In [19]:
arr6[0][0][0:3] = 68
# np.array数组可以逐层访问，我们可以对最后面也就是一维的数组进行切片
arr6[0][0]

array([68, 68, 68])

In [20]:
arr6[0,0,0]# 这种访问方式也是可行的！！！

68

In [21]:
arr6.astype('float')

array([[[68., 68., 68.],
        [ 4.,  5.,  6.]],

       [[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]]])

In [22]:
arr6[1:3,1:2,2:3]
# 所以啊这个多维数组的切片，我们需要切多次，按照从外而内的切片方式，就想上面这样，把最外面的当成一个个小元素去切片，然后再往下切，再往下且切，and so on
# 只有冒号叫做全部都取。。。

array([[[6]],

       [[6]]])

### 布尔型索引

In [23]:
names = ['huangxingjie','lisimao','oulaoula','bidagelasi']
arrname = np.array(names,dtype='|S4')
arrname

array([b'huan', b'lisi', b'oula', b'bida'], dtype='|S4')

In [24]:
dataran = np.random.randn(7,4)
dataran

array([[ 0.47116176, -1.21194596,  1.3178383 ,  0.56050715],
       [ 0.93333386,  0.04668959,  0.06911546,  0.6282774 ],
       [-0.98117414, -0.20769335,  0.55723577, -0.47058225],
       [ 0.06638951, -0.41420124, -2.63871424, -0.11684062],
       [ 1.81267143,  0.03244659,  0.55872532,  0.43446075],
       [ 0.34565308, -0.90728612,  1.76517846,  0.36609246],
       [-0.58792069, -0.19705419, -0.08340418,  1.18621702]])

In [25]:
names == 'huangxingjie'

False

In [26]:
dataran > 0

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True, False],
       [ True, False, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [False, False, False,  True]])

python中的关键字 and or 在布尔型数组中失效 而是要用& | 来表示。


In [27]:
# 使用这种方法可以把数组里面的所有你不想看见的数据处理然后换成你想看见的值
dataran[dataran < 0] = 0
dataran

array([[0.47116176, 0.        , 1.3178383 , 0.56050715],
       [0.93333386, 0.04668959, 0.06911546, 0.6282774 ],
       [0.        , 0.        , 0.55723577, 0.        ],
       [0.06638951, 0.        , 0.        , 0.        ],
       [1.81267143, 0.03244659, 0.55872532, 0.43446075],
       [0.34565308, 0.        , 1.76517846, 0.36609246],
       [0.        , 0.        , 0.        , 1.18621702]])

### 花式索引(fancy indexing)

In [28]:
arr7 = np.empty((7,4))

In [29]:
for i in range(7):
    arr7[i] = i
arr7

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [30]:
# array[[放索引值可以按你想要的顺序去打印！！！]]
arr8 = arr7[[6,5,3]]
arr8

array([[6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [31]:
arr9 = np.arange(32).reshape((4,8))
arr9

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [32]:
# 转置矩阵。
arr9.T

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [33]:
# transpose函数在使用时不应该超过所属的维度范围，超过就报错，应该是满足矩阵的线性变换的！！
arr9.transpose((0,1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

### 一元ufunc
|函数|说明|
|:-|:-|
|abs,fabs|计算整数，浮点数或者符数的绝对值，对于非复数值，可以使用更快的fabs|
|sqrt|计算个元素的平方根，相当于arr**0.5|
|square|计算各个元素的平方，相当于arr**2|
|exp|计算个元素的指数e^x|
|log,log10,log2,log1p|分别为自然对数，底数为10，2，log(1+x)|
|sign|计算各个元素的正负号，1(整数)，0(零)，-1(负数)|
|ceil|计算个元素的ceiling值，即大于该值的最小整数|
|floor|计算各个元素的floor值，即小于该值的最大整数|
|rint|将个元素的值四舍五入后到最接近的整数，保留dtype|
|modf|将数组的小数和整数部分以两个独立的形式返回|
|isnan|返回一个表示"哪些值是NaN(这不是一个数字)"的布尔型数组|
|isfinite,isint|分别返回一个表示"哪些元素是有穷的(非inf，非NaN)"或者是哪些元素是无穷的布尔型数组|
|cos,cosh,sin,sinh,tan,tanh|普通三角函数，与双曲型三角函数|
|arcsin,arccos,arctan,arcsinh,arccosh,arctanh|反三角函数与反双曲型三角函数|
|local_not|计算各个元素的not x的真值，相当于-arr|


### 二元ufunc
|函数|说明|
|:-|:-|
|add|将数组中的对应元素相加|
|subtarct|从第一个数组中减去第二个数组中的元素|
|multiply|数组元素对应相乘|
|divide，floor_divide|除法或者向下圆除法(丢弃余数)|
|power|对第一个数组的元素A，根据第二个数组中的相应元素B，计算A^B|
|maximum,fmax|元素级的最大值计算。fmax将忽略NaN|
|minimun,fmin|同上|
|mod|元素级别的求模运算|
|copysign|将第二个数组中的值的符号复制给第一个数组中的值|
|greater，greater_equal,less，less_equal,equal,not_equal|执行元素级别的比较运算，最终产生的是布尔型的数组，相当于比较运算符|
|local_and,local_or,local_xor|执行元素级别的真逻辑运算，相当于中缀运算符 &，|，^|

