## IPython 学习笔记：
>   IPython是一种更加高级的Python终端，使用数据分析时需要一步一步的操作并且可视化
>   得出结论，这样让我们的代码编写，趋势分析更加直观。

In [1]:
import numpy as np
data1 = np.random.randn(3,3)
data1

array([[ 0.55983816,  0.78290576,  0.05161188],
       [ 1.10237729, -0.67975395,  0.50692035],
       [-1.21252783, -0.48341164,  0.55360927]])

* numpy.random的randn()函数：
        np.random.randn()表示生成一个正态分布数字，
        np.random.randn(x,y,z...,...)这个表示生成一个高维的正态矩阵
* numpy.random的rand()函数：
        np.random.rand()与上面相同但区别是rand只导出[0,1)之间的随机数维度自定。

In [2]:
data2 = np.random.rand(2,2)
data2

array([[0.99086421, 0.45863485],
       [0.51824138, 0.64899216]])

* numpy.random的randint()函数:
        np.random.randint(low,high=NONE,size=NONE,dtype='l')
        顾名思义，随机一个整数，[low,high),
        size为数组维度
        dtype是数据类型，一般默认为np.int类型。
        当high没有填时我们的范围就是[0,low)的随机数。



In [3]:
data3 = np.random.randint(10,high=50,size=[10,10],dtype='l')
data3

array([[25, 47, 49, 36, 25, 15, 40, 37, 28, 22],
       [40, 27, 16, 37, 29, 15, 49, 19, 23, 15],
       [49, 35, 43, 22, 12, 47, 41, 19, 43, 46],
       [48, 24, 26, 43, 38, 23, 25, 32, 32, 42],
       [38, 49, 45, 28, 25, 14, 23, 16, 24, 33],
       [14, 43, 29, 16, 35, 37, 40, 12, 40, 46],
       [25, 39, 37, 20, 44, 28, 10, 38, 14, 34],
       [30, 10, 42, 22, 22, 30, 29, 39, 38, 34],
       [20, 44, 46, 32, 24, 16, 13, 29, 13, 14],
       [36, 34, 46, 19, 36, 48, 45, 38, 27, 17]])

* numpy.random.random_sample()函数：
        numpy.random.random_sample():这个函数可以返回一个随机浮点数，如果不给任
        何参数的，他将会返回一个[0，1) 的随机值，如果加上了数字，将返回多个数字。再在外面
        乘以相应的数值则可以得到[0,n)
        n * np.random.random_sample()
        > 使用size参数可以实现矩阵维度的变换！！
        np.random.random_sample(size=(n,m))

In [4]:
data4 = np.random.random_sample(5)
data4

array([0.42346371, 0.62762543, 0.66890128, 0.47057324, 0.10187241])

In [5]:
data5 = np.random.random_sample(size=(5,5))
data5

array([[0.13168809, 0.24844435, 0.64111001, 0.35757568, 0.23349179],
       [0.76536068, 0.02218345, 0.21940744, 0.77600919, 0.71351319],
       [0.60269052, 0.02495334, 0.54757108, 0.63020527, 0.44957572],
       [0.07321899, 0.57168513, 0.89626056, 0.00698437, 0.48810109],
       [0.55714143, 0.93208671, 0.33911488, 0.80164613, 0.03345411]])

* numpy.random.choice(a, size=None, replace=True, p=None)
        a:表示数字[0,a)的之中的整数，a同样可以表示一个列表，从而实现物理随机选择
        size：与上面的size相同表示维度大小
        replace:这个与重复数字有关联，如果replace=False,那么就不允许重复数据的存在



In [7]:
array1 = ['a','b','c','d']
data6 = np.random.choice(array1,size=(3,3))
data6

array([['b', 'a', 'a'],
       ['c', 'b', 'a'],
       ['c', 'c', 'd']], dtype='<U1')

```python
b = [1,2,3,4,5,6]
# b.<TAB>可以实现对各种方法的快速查询。
```


In [10]:
b = [1,2,3,4,5,6]
# b? 这样可以实现对b的详细信息的查询。

In [1]:
c = [1,2,3,4,5,6]
# np.*load*?
# 这样可以查询包含这个的函数们。
# %run balabala.py这样可以实现代码的运行
# Ctrl + C 终止正在运行的代码
# %paste魔法函数可以复制粘贴板中的一切！！

%time 和 %timeit这两个魔法函数可以让你知道程序运行的时间。



In [5]:
strings = ['foo', 'foobar', 'baz', 'qux', 'python'] * 10000
%time method1 = [x for x in strings if x.startswith('foo')]
# 这里的startwith函数可以帮助我们判断是否这个列表开始于这个前缀，是则返回True否则False
%timeit method2 = [x for x in strings if x[:3] == 'foo']


4.27 ms ± 32.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.89 ms ± 54.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
